---
apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  type: LoadBalancer
  selector:
    app: simpleservice
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080